# Generated by Django 2.2.6 on 2019-12-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SBN', models.IntegerField()),
                ('Investment_Promotion', models.CharField(max_length=200)),
                ('Legal_Basis', models.CharField(max_length=200)),
                ('Incentive_Start', models.DateField()),
                ('Incentive_End', models.DateField()),
                ('Incentive_Granted', models.CharField(max_length=200)),
                ('Accreditation_Number', models.IntegerField()),
                ('Facility_Code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DLN', models.IntegerField()),
                ('Single_Business_Number', models.IntegerField()),
                ('Registering_Office', models.CharField(max_length=200)),
                ('BIR_Registration_Date', models.DateField(verbose_name='BIR Registration Date')),
                ('TIN', models.IntegerField()),
                ('RDO_CODE', models.CharField(max_length=200)),
                ('Municipality_Code', models.CharField(max_length=200)),
                ('ID_Type', models.CharField(max_length=200)),
                ('ID_Number', models.IntegerField()),
                ('Date_of_Payment', models.DateField(verbose_name='Date of Payment')),
            ],
        ),
        migrations.CreateModel(
            name='Taxpayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIN', models.IntegerField()),
                ('PSN', models.IntegerField()),
                ('Tax_Type', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
                ('Civil_Status', models.CharField(max_length=200)),
                ('Birthday', models.DateField(verbose_name='Birthday')),
                ('Citizenship', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Avail_Income_Tax', models.BooleanField()),
            ],
        ),
    ]
