# Generated by Django 2.2.6 on 2019-12-03 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='Single_Business_Number',
            new_name='SBN',
        ),
    ]
