# Generated by Django 2.2.6 on 2019-12-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_auto_20191203_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='SBN',
            field=models.ForeignKey(on_delete='CASCADE', to='taxes.Business'),
        ),
        migrations.AlterField(
            model_name='document',
            name='TIN',
            field=models.OneToOneField(on_delete='CASCADE', to='taxes.Taxpayer'),
        ),
    ]
