# Generated by Django 2.2.6 on 2019-12-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0005_auto_20191203_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxpayer',
            name='Avail_Income_Tax',
        ),
    ]
