# Generated by Django 2.2.6 on 2019-12-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0006_remove_taxpayer_avail_income_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='Incentive_End',
        ),
        migrations.RemoveField(
            model_name='business',
            name='Incentive_Granted',
        ),
        migrations.RemoveField(
            model_name='business',
            name='Incentive_Start',
        ),
        migrations.RemoveField(
            model_name='business',
            name='Investment_Promotion',
        ),
        migrations.RemoveField(
            model_name='business',
            name='Legal_Basis',
        ),
    ]
