# Generated by Django 2.2.6 on 2019-12-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0007_auto_20191203_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='Date_of_Payment',
        ),
        migrations.RemoveField(
            model_name='document',
            name='ID_Number',
        ),
        migrations.RemoveField(
            model_name='document',
            name='ID_Type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='Municipality_Code',
        ),
        migrations.RemoveField(
            model_name='document',
            name='RDO_Code',
        ),
        migrations.RemoveField(
            model_name='taxpayer',
            name='Citizenship',
        ),
        migrations.RemoveField(
            model_name='taxpayer',
            name='PSN',
        ),
        migrations.RemoveField(
            model_name='taxpayer',
            name='Tax_Type',
        ),
    ]
