# Generated by Django 2.2.6 on 2019-12-03 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0012_auto_20191204_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='SBN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxes.Business'),
        ),
        migrations.AlterField(
            model_name='document',
            name='TIN',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taxes.Taxpayer'),
        ),
    ]
