# Generated by Django 2.2.6 on 2019-12-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0014_auto_20191204_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='SBN',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='DLN',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='TIN',
            field=models.IntegerField(unique=True),
        ),
    ]
