# Generated by Django 2.2.6 on 2019-12-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0015_auto_20191204_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='SBN',
            field=models.ForeignKey(on_delete='CASCADE', to='taxes.Business'),
        ),
        migrations.AlterField(
            model_name='document',
            name='TIN',
            field=models.ForeignKey(on_delete='CASCADE', to='taxes.Taxpayer'),
        ),
    ]
